<a href="https://colab.research.google.com/github/sjagadee/py_torch_from_basics/blob/main/01_tensors_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.11.0+cu128


This section checks the PyTorch version and GPU availability.

In [ ]:
if torch.cuda.is_available():
    print("GPU is available")
    print("GPU name:", torch.cuda.get_device_name(0))
else:
    print("GPU is not available")

GPU is available
GPU name: Tesla T4


## Creating Tensors
This section demonstrates various ways to create tensors in PyTorch, including using `empty`, `zeros`, `ones`, `rand`, `manual_seed`, `tensor`, `arange`, `linspace`, `eye`, and `full`.

In [ ]:
# using empty

a = torch.empty(2,3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# type
type(a)

torch.Tensor

In [ ]:
# create tensor using zero
z = torch.zeros(2,3)
z

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# create tensor using ones
o = torch.ones(2,3)
o

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# create tensor using rand
r = torch.rand(2,3)
r

tensor([[0.3987, 0.3246, 0.7645],
        [0.5311, 0.6265, 0.8689]])

Using `torch.manual_seed` ensures reproducibility of random tensor generation.

In [ ]:
# create tensor using manual seed
torch.manual_seed(1729)
r = torch.rand(2,3)
r

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])

In [ ]:
# using tensor to create tensor
t = torch.tensor([[1,2,3],[4,5,6]])
t

tensor([[1, 2, 3],
        [4, 5, 6]])

Directly creating a tensor from a Python list or NumPy array.

In [ ]:
# other ways

# arange - start end with step size (step: increment size)
print("Using arange:", torch.arange(10))
print("Using arange:", torch.arange(4,10))
print("Using arange:", torch.arange(1,5,0.5))

Using arange: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Using arange: tensor([4, 5, 6, 7, 8, 9])
Using arange: tensor([1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000, 4.5000])


In [ ]:
# linspace - start to end - evenly spaced values
print("Using linspace:", torch.linspace(1,10,5))
print("Using linspace:", torch.linspace(0, 10, 10))

Using linspace: tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])
Using linspace: tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])


`torch.linspace` generates evenly spaced values within a specified interval.

In [ ]:
# using eye
print("Using eye:", torch.eye(3))
print("Using eye:", torch.eye(5,4))

Using eye: tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
Using eye: tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 0.]])


`torch.eye` creates an identity matrix or a matrix with ones on the diagonal.

In [ ]:
# using full
print("Using full:", torch.full((2,3), 3))

Using full: tensor([[3, 3, 3],
        [3, 3, 3]])


`torch.full` creates a tensor of a specified size filled with a given value.

## Tensor Shape
This section explores how to check and manipulate the shape of tensors, as well as creating new tensors based on the shape of existing ones.

In [ ]:
t = torch.tensor([[1,2,3],[4,5,6]])
t

tensor([[1, 2, 3],
        [4, 5, 6]])

Creating a sample tensor to demonstrate shape operations.

In [ ]:
t.shape

torch.Size([2, 3])

Checking the shape of the tensor.

In [ ]:
# creating an empty tensor based on other tensor
t_empty = torch.empty_like(t)
t_empty

tensor([[        0, 638940800,         0],
        [        0,         0,         0]])

Creating new tensors with the same shape as an existing tensor, but filled with empty (uninitialized), zeros, ones, or random values.

In [ ]:
# creating an zeros tensor based on other tensor
t_zeros = torch.zeros_like(t)
t_zeros

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
# creating an ones tensor based on other tensor
t_ones = torch.ones_like(t)
t_ones

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
# creating an random tensor based on other tensor
# t_rand = torch.rand_like(t)
t_rand = torch.rand_like(t, dtype=torch.float32)
t_rand

tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])

## Datatypes in PyTorch
This section covers how to inspect and change the data types of tensors.

In [ ]:
# find datatypes

print(t)
print(t.dtype)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.int64


Finding the data type of an existing tensor.

In [ ]:
# assign datatype during creation

t_int = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.int)
t_int

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

Assigning a specific data type during tensor creation.

In [ ]:
t_float = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32)
t_float

tensor([[1., 2., 3.],
        [4., 5., 6.]])

Changing the data type of an existing tensor using the `.to()` method.

In [ ]:
# assing datatype for a tensor
t_new_float = t.to(torch.float64)
t_new_float

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

Here is your PyTorch data type reference formatted into a clean, readable table:

| Data Type | Dtype | Description |
| --- | --- | --- |
| **32-bit Floating Point** | `torch.float32` | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage. |
| **64-bit Floating Point** | `torch.float64` | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory. |
| **16-bit Floating Point** | `torch.float16` | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs. |
| **BFloat16** | `torch.bfloat16` | Brain floating-point format with reduced precision compared to float16. Used in mixed-precision training, especially on TPUs. |
| **8-bit Floating Point** | `torch.float8` | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common). |
| **8-bit Integer** | `torch.int8` | 8-bit signed integer. Used for quantized models to save memory and computation in inference. |
| **16-bit Integer** | `torch.int16` | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision. |
| **32-bit Integer** | `torch.int32` | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks. |
| **64-bit Integer** | `torch.int64` | Long integer type. Often used for large indexing arrays or for tasks involving large numbers. |
| **8-bit Unsigned Integer** | `torch.uint8` | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255). |
| **Boolean** | `torch.bool` | Boolean type, stores `True` or `False` values. Often used for masks in logical operations. |
| **Complex 64** | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks. |
| **Complex 128** | `torch.complex128` | Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory. |
| **Quantized Integer** | `torch.qint8` | Quantized signed 8-bit integer. Used in quantized models for efficient inference. |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks. |

## Mathematical Operations in PyTorch
This section demonstrates various mathematical operations that can be performed on PyTorch tensors.

### Scalar Operations
These operations apply a scalar value to each element of a tensor.

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

Creating a sample tensor for scalar operations.

In [ ]:
# addition
x + 2

tensor([[3, 4, 5],
        [6, 7, 8]])

In [ ]:
# subtraction
x - 2

tensor([[-1,  0,  1],
        [ 2,  3,  4]])

In [ ]:
# multiplication
x * 4

tensor([[ 4,  8, 12],
        [16, 20, 24]])

In [ ]:
# division
x / 3

tensor([[0.3333, 0.6667, 1.0000],
        [1.3333, 1.6667, 2.0000]])

In [ ]:
# integer division
(x * 20) // 3

tensor([[ 6, 13, 20],
        [26, 33, 40]])

In [ ]:
# modulo
((x * 20) // 3) % 4

tensor([[2, 1, 0],
        [2, 1, 0]])

In [ ]:
# power
x ** 3

tensor([[  1,   8,  27],
        [ 64, 125, 216]])

### Element-wise operations on tensors
These operations are performed element by element between two tensors of the same shape.

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)
print(a)
print(b)

tensor([[0.6128, 0.1519, 0.0453],
        [0.5035, 0.9978, 0.3884]])
tensor([[0.6929, 0.1703, 0.1384],
        [0.4759, 0.7481, 0.0361]])


Creating two random tensors for element-wise operations.

In [ ]:
# add
a + b

tensor([[1.3057, 0.3223, 0.1838],
        [0.9794, 1.7459, 0.4245]])

In [ ]:
# sub
a - b

tensor([[-0.0801, -0.0184, -0.0931],
        [ 0.0276,  0.2498,  0.3523]])

In [ ]:
# multiply
a * b

tensor([[0.4246, 0.0259, 0.0063],
        [0.2396, 0.7464, 0.0140]])

In [ ]:
# division
a / b

tensor([[ 0.8844,  0.8920,  0.3275],
        [ 1.0580,  1.3339, 10.7529]])

In [ ]:
# mod
a % b

tensor([[0.6128, 0.1519, 0.0453],
        [0.0276, 0.2498, 0.0272]])

In [ ]:
# pow
a ** b

tensor([[0.7122, 0.7254, 0.6516],
        [0.7214, 0.9984, 0.9664]])

### Some operations on a single tensor
These are mathematical functions applied to each element of a single tensor.

In [ ]:
# some operation on single tensor
# absolute value
c = torch.tensor([1, -3, 5, -9])
torch.abs(c)

tensor([1, 3, 5, 9])

Demonstrating `abs` and `neg` on an integer tensor.

In [ ]:
# negative
torch.neg(c)

tensor([-1,  3, -5,  9])

In [ ]:
d = torch.tensor([3.6, 4.3, 5.9, 2.1])
d

tensor([3.6000, 4.3000, 5.9000, 2.1000])

Demonstrating rounding functions (`round`, `floor`, `ceil`) and `clamp` on a float tensor.

In [ ]:
# round
torch.round(d)

tensor([4., 4., 6., 2.])

In [ ]:
# floor
torch.floor(d)

tensor([3., 4., 5., 2.])

In [ ]:
# ceiling
torch.ceil(d)

tensor([4., 5., 6., 3.])

In [ ]:
# clamp - set the tensor values in a range
torch.clamp(d, min=2, max=4)

tensor([3.6000, 4.0000, 4.0000, 2.1000])

### Reduction operations
These operations reduce the dimensions of a tensor by applying a function (like sum, mean, min, max, etc.) along a specified dimension or over all elements.

Creating a random integer tensor for reduction operations.

In [ ]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[3., 2., 7.],
        [4., 9., 0.]])

Calculating the sum of all elements, sum along columns (dim=0), and sum along rows (dim=1).

In [ ]:
# sum
print(torch.sum(e))

# sum of columns
print(torch.sum(e, dim=0))

# sum of rows
print(torch.sum(e, dim=1))

tensor(25.)
tensor([ 7., 11.,  7.])
tensor([12., 13.])


Calculating the mean of all elements, mean along columns, and mean along rows.

In [ ]:
# mean
print(torch.mean(e))

# mean of columns
print(torch.mean(e, dim=0))

# mean of rows
print(torch.mean(e, dim=1))

tensor(4.1667)
tensor([3.5000, 5.5000, 3.5000])
tensor([4.0000, 4.3333])


Calculating the median of all elements, median along columns, and median along rows. Note that `torch.median` returns both the values and their indices.

In [ ]:
# median
print(torch.median(e))

# median of columns
print(torch.median(e, dim=0))

# median of rows
print(torch.median(e, dim=1))

tensor(3.)
torch.return_types.median(
values=tensor([3., 2., 0.]),
indices=tensor([0, 0, 1]))
torch.return_types.median(
values=tensor([3., 4.]),
indices=tensor([0, 0]))


Finding the minimum and maximum values in the tensor.

In [ ]:
# min and max
print(torch.min(e))
print(torch.max(e))

tensor(0.)
tensor(9.)


Calculating the product of all elements, product along columns, and product along rows.

In [ ]:
# product
print(torch.prod(e))

# product of columns
print(torch.prod(e, dim=0))

# product of rows
print(torch.prod(e, dim=1))

tensor(0.)
tensor([12., 18.,  0.])
tensor([42.,  0.])


Calculating the standard deviation of all elements, standard deviation along columns, and standard deviation along rows.

In [ ]:
# standard deviation
print(torch.std(e))

# standard deviation of columns
print(torch.std(e, dim=0))

# standard deviation of rows
print(torch.std(e, dim=1))

tensor(3.3116)
tensor([0.7071, 4.9497, 4.9497])
tensor([2.6458, 4.5092])


Calculating the variance of all elements, variance along columns, and variance along rows.

In [ ]:
# variance
print(torch.var(e))

# variance of columns
print(torch.var(e, dim=0))

# variance of rows
print(torch.var(e, dim=1))

tensor(10.9667)
tensor([ 0.5000, 24.5000, 24.5000])
tensor([ 7.0000, 20.3333])


Finding the index of the maximum value (`argmax`) along different dimensions.

In [ ]:
# argmax
print(torch.argmax(e))
print(torch.argmax(e, dim=0))
print(torch.argmax(e, dim=1))

tensor(4)
tensor([1, 1, 0])
tensor([2, 1])


Finding the index of the minimum value (`argmin`) along different dimensions.

In [ ]:
# argmin
print(torch.argmin(e))
print(torch.argmin(e, dim=0))
print(torch.argmin(e, dim=1))

tensor(5)
tensor([0, 0, 1])
tensor([1, 2])


### Matrix Operations
This section demonstrates common matrix operations such as multiplication, dot product, transpose, determinant, and inverse.

Creating two random tensors suitable for matrix multiplication.

In [ ]:
m = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
n = torch.randint(size=(3,2), low=0, high=10, dtype=torch.float32)

print(m)
print(n)

tensor([[7., 5., 7.],
        [3., 0., 4.]])
tensor([[0., 1.],
        [9., 8.],
        [6., 7.]])


Performing matrix multiplication using `torch.matmul`.

In [ ]:
# matrix multiplication
torch.matmul(m, n)

tensor([[87., 96.],
        [24., 31.]])

Calculating the dot product of two 1D tensors (vectors).

In [ ]:
v1 = torch.tensor([1, 2])
v2 = torch.tensor([3, 4])

# dot product
torch.dot(v1, v2)

tensor(11)

Transposing a matrix using `torch.t`.

In [ ]:
# transpose
print(m)

print(torch.t(m))

tensor([[7., 5., 7.],
        [3., 0., 4.]])
tensor([[7., 3.],
        [5., 0.],
        [7., 4.]])


Calculating the determinant of a square matrix using `torch.linalg.det`.

In [ ]:
# determinent

h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
print(h)

print(torch.linalg.det(h))

tensor([[4., 2., 0.],
        [4., 8., 9.],
        [9., 5., 3.]])
tensor(54.)


Calculating the inverse of a square matrix using `torch.linalg.inv`.

In [ ]:
# inverse
print(torch.linalg.inv(h))

tensor([[-0.3889, -0.1111,  0.3333],
        [ 1.2778,  0.2222, -0.6667],
        [-0.9630, -0.0370,  0.4444]])


### Comparison Operations
This section demonstrates how to compare tensors element-wise.

Creating two random tensors for comparison.

In [ ]:
i = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
j = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)

print(i)
print(j)

tensor([[0., 3., 7.],
        [2., 2., 9.]])
tensor([[3., 6., 4.],
        [4., 3., 5.]])


Performing element-wise comparisons (`>`, `<`, `==`, `!=`, `>=`, `<=`).

In [ ]:
# greater than
i > j

tensor([[False, False,  True],
        [False, False,  True]])

In [ ]:
# less than
i < j

tensor([[ True,  True, False],
        [ True,  True, False]])

In [ ]:
# equal to
i == j

tensor([[False, False, False],
        [False, False, False]])

In [ ]:
# not equal to
i != j

tensor([[True, True, True],
        [True, True, True]])

In [ ]:
# greater than or equal to
i >= j

tensor([[False, False,  True],
        [False, False,  True]])

In [ ]:
# less than or equal to
i <= j

tensor([[ True,  True, False],
        [ True,  True, False]])

### Special functions
This section covers various non-linear and activation functions commonly used in deep learning.

Creating a sample tensor for special functions.

In [ ]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[2., 1., 3.],
        [5., 4., 5.]])

Applying common mathematical functions like `log`, `exp`, `sqrt`, `sigmoid`, `softmax`, and `relu`.

In [ ]:
#log
torch.log(k)

tensor([[0.6931, 0.0000, 1.0986],
        [1.6094, 1.3863, 1.6094]])

In [ ]:
# exp
torch.exp(k)

tensor([[  7.3891,   2.7183,  20.0855],
        [148.4132,  54.5981, 148.4132]])

In [ ]:
# sqrt
torch.sqrt(k)

tensor([[1.4142, 1.0000, 1.7321],
        [2.2361, 2.0000, 2.2361]])

In [ ]:
# sigmoid
torch.sigmoid(k)

tensor([[0.8808, 0.7311, 0.9526],
        [0.9933, 0.9820, 0.9933]])

In [ ]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.0474, 0.0474, 0.1192],
        [0.9526, 0.9526, 0.8808]])

In [ ]:
# relu
torch.relu(k)

tensor([[2., 1., 3.],
        [5., 4., 5.]])

## Inplace Operations
Inplace operations modify the tensor directly without creating a new one, which can save memory. They are often denoted by a trailing underscore (e.g., `add_`).

Creating two random tensors to demonstrate inplace operations.

In [ ]:
x = torch.rand(2, 4)
y = torch.rand(2, 4)
print(x)
print(y)

tensor([[0.3857, 0.9883, 0.4762, 0.7242],
        [0.0776, 0.4004, 0.9877, 0.0352]])
tensor([[0.0905, 0.4485, 0.8740, 0.2526],
        [0.6923, 0.7545, 0.7746, 0.2330]])


Normal addition creates a new tensor, consuming extra memory.

In [ ]:
x + y # here it is creating an extra space to save this in memory

tensor([[0.4762, 1.4369, 1.3502, 0.9768],
        [0.7699, 1.1549, 1.7623, 0.2682]])

Using `x.add_(y)` performs addition inplace, modifying `x` directly.

In [ ]:
# use inplace op
x.add_(y)

tensor([[0.4762, 1.4369, 1.3502, 0.9768],
        [0.7699, 1.1549, 1.7623, 0.2682]])

In [ ]:
x

tensor([[0.4762, 1.4369, 1.3502, 0.9768],
        [0.7699, 1.1549, 1.7623, 0.2682]])

In [ ]:
y

tensor([[0.0905, 0.4485, 0.8740, 0.2526],
        [0.6923, 0.7545, 0.7746, 0.2330]])

Applying an inplace sigmoid activation function to `y`.

In [ ]:
y.sigmoid_()

tensor([[0.5226, 0.6103, 0.7056, 0.5628],
        [0.6665, 0.6802, 0.6845, 0.5580]])

In [ ]:
y

tensor([[0.5226, 0.6103, 0.7056, 0.5628],
        [0.6665, 0.6802, 0.6845, 0.5580]])

## Copy a tensor
This section explains the difference between assigning a tensor to a new variable (which creates a reference) and cloning a tensor (which creates a deep copy).

In [ ]:
r = torch.rand(2, 3)
r

tensor([[0.5183, 0.9807, 0.6545],
        [0.4144, 0.0696, 0.4648]])

Creating a sample tensor `r`.

In [ ]:
s = r

Assigning `r` to `s` creates a reference, so `s` points to the same memory as `r`.

In [ ]:
r[0][0] = 399

Modifying `r` will also change `s`.

In [ ]:
r

tensor([[3.9900e+02, 9.8070e-01, 6.5449e-01],
        [4.1437e-01, 6.9621e-02, 4.6479e-01]])

In [ ]:
s

tensor([[3.9900e+02, 9.8070e-01, 6.5449e-01],
        [4.1437e-01, 6.9621e-02, 4.6479e-01]])

Confirming that `r` and `s` have the same memory ID.

In [ ]:
id(r) == id(s)

True

Using `clone()` creates a new tensor `s` with a separate copy of the data from `r`.

In [ ]:
s = r.clone()

Modifying `r` after cloning will not affect `s`.

In [ ]:
r[0][0] = 10

In [ ]:
r

tensor([[10.0000,  0.9807,  0.6545],
        [ 0.4144,  0.0696,  0.4648]])

In [ ]:
s

tensor([[3.9900e+02, 9.8070e-01, 6.5449e-01],
        [4.1437e-01, 6.9621e-02, 4.6479e-01]])

Confirming that `r` and `s` now have different memory IDs.

In [ ]:
id(r) == id(s)

False

## Tensor operations on GPU
This section demonstrates how to move tensors to a GPU and perform operations on them, highlighting the potential speedup.

Checking if a CUDA-enabled GPU is available.

In [ ]:
torch.cuda.is_available()

True

Setting the device to `cuda` if a GPU is available.

In [ ]:
device = torch.device("cuda")

Creating a new tensor directly on the GPU.

In [ ]:
# creating new tensor on GPU
torch.rand((2,3), device=device)

tensor([[0.3344, 0.2640, 0.2119],
        [0.0582, 0.3720, 0.1818]], device='cuda:0')

Moving an existing tensor (`s`) from CPU to GPU using the `.to()` method.

In [ ]:
# lets move s tensor to GPU
n_t = s.to(device)

Benchmarking matrix multiplication performance on CPU versus GPU.

In [ ]:
n_t

tensor([[3.9900e+02, 9.8070e-01, 6.5449e-01],
        [4.1437e-01, 6.9621e-02, 4.6479e-01]], device='cuda:0')

In [ ]:
# lets compare CPU vs GPU speed
import time

size = 10000

x = torch.rand(size, size)
y = torch.rand(size, size)

start = time.time()
mat_mul_cpu = torch.matmul(x, y)
end = time.time()

cpu_time = end - start

print(f"CPU time: {cpu_time}")

x_gpu = x.to(device)
y_gpu = y.to(device)

start = time.time()
mat_mul_gpu = torch.matmul(x_gpu, y_gpu)
torch.cuda.synchronize()
end = time.time()

gpu_time = end - start

print(f"GPU time: {gpu_time}")

print(f"Speedup: {cpu_time/gpu_time}")

CPU time: 18.98593282699585
GPU time: 0.5363762378692627
Speedup: 35.39667025969841


## Reshaping Tensors
This section demonstrates various methods for changing the shape and dimensions of tensors.

Creating a sample tensor for reshaping operations.

In [ ]:
w = torch.ones(4, 4)
w

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Reshaping a tensor into a new shape. The total number of elements must remain the same.

In [ ]:
# reshape
w.reshape(2, 2, 2, 2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

Flattening a tensor into a 1D tensor.

In [ ]:
# flatten
w.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Permuting the dimensions of a tensor. This is useful for reordering axes, e.g., for image processing where channels might need to be moved.

In [ ]:
# permute
u = torch.rand(2, 3, 4)
u

tensor([[[0.5167, 0.9368, 0.4163, 0.4929],
         [0.5812, 0.3740, 0.1104, 0.9614],
         [0.8492, 0.0620, 0.5500, 0.5217]],

        [[0.8517, 0.4423, 0.6955, 0.0643],
         [0.2892, 0.7425, 0.3974, 0.8278],
         [0.3057, 0.2695, 0.9759, 0.7739]]])

In [ ]:
u.permute(2, 0, 1).shape

torch.Size([4, 2, 3])

Adding a singleton dimension to a tensor using `unsqueeze`.

In [ ]:
u.permute(2, 0, 1)

tensor([[[0.5167, 0.5812, 0.8492],
         [0.8517, 0.2892, 0.3057]],

        [[0.9368, 0.3740, 0.0620],
         [0.4423, 0.7425, 0.2695]],

        [[0.4163, 0.1104, 0.5500],
         [0.6955, 0.3974, 0.9759]],

        [[0.4929, 0.9614, 0.5217],
         [0.0643, 0.8278, 0.7739]]])

In [ ]:
# unsqueeze
v = torch.rand(256, 256, 3)
v.shape

torch.Size([256, 256, 3])

Removing singleton dimensions from a tensor using `squeeze`.

In [ ]:
v.unsqueeze(dim=0).shape

torch.Size([1, 256, 256, 3])

In [ ]:
# squeeze
w = torch.rand(1, 20)
w.squeeze(dim=0).shape

torch.Size([20])

## NumPy to Torch and vice-versa
This section demonstrates how to convert between PyTorch tensors and NumPy arrays.

Converting a PyTorch tensor to a NumPy array using `.numpy()`.

In [ ]:
d = torch.tensor([1, 2, 4, 7])
d

tensor([1, 2, 4, 7])

Converting a NumPy array to a PyTorch tensor using `torch.from_numpy()`.

In [ ]:
d.numpy()

array([1, 2, 4, 7])

In [ ]:
import numpy

e = numpy.array([1, 2, 4, 7])
e

array([1, 2, 4, 7])

In [ ]:
torch.from_numpy(e)

tensor([1, 2, 4, 7])