<a href="https://colab.research.google.com/github/sjagadee/py_torch_from_basics/blob/main/04_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
! pip install torchinfo

In [30]:
import torch, torch.nn as nn
from torchinfo import summary

In [31]:
# Define a simple linear model using nn.Module
class Model(nn.Module):

    # Initialize the model with the number of input features
    def __init__(self, no_of_features):
        super().__init__()
        # Define a linear layer that maps 'no_of_features' to 1 output
        self.linear = nn.Linear(no_of_features, 1)
        # Define a sigmoid activation function
        self.sigmoid = nn.Sigmoid()

    # Define the forward pass of the model
    def forward(self, feature):
        out = self.linear(feature) # Apply linear transformation (wx + b)
        out = self.sigmoid(out)    # Apply sigmoid activation to the output
        return out

In [32]:
# Create a dummy dataset with 10 samples and 5 features
features = torch.rand(10, 5)

# Create an instance of the Model
model = Model(features.shape[1]) # Pass the number of features (5) to the model

# Call the model's forward pass to get an output
# The __call__ method of nn.Module automatically invokes the forward method
# model.forward(features) # This is equivalent but less common
output = model(features)
print("Output from Model:\n", output)

Output from Model:
 tensor([[0.4283],
        [0.5179],
        [0.4523],
        [0.4418],
        [0.4908],
        [0.3819],
        [0.4018],
        [0.4463],
        [0.4818],
        [0.4526]], grad_fn=<SigmoidBackward0>)


In [33]:
# Access and print the weights and biases of the linear layers in Model
print("Linear weights:\n", model.linear.weight)
print("Linear bias:\n",model.linear.bias)

Linear weights:
 Parameter containing:
tensor([[ 0.2573, -0.2452,  0.2411,  0.1631, -0.0236]], requires_grad=True)
Linear bias:
 Parameter containing:
tensor([-0.3742], requires_grad=True)


In [34]:
# Display a summary of the Model architecture
# input_size specifies the shape of a single input batch (batch_size, num_features)
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [35]:
# Define a multi-layer perceptron (MLP) model with one hidden layer
class Model2(nn.Module):

    # Initialize the model with the number of input features
    def __init__(self, no_of_features):
        super().__init__()
        # First linear layer: input features to 3 hidden units
        self.linear1 = nn.Linear(no_of_features, 3)
        # ReLU activation for the hidden layer
        self.relu = nn.ReLU()
        # Second linear layer: 3 hidden units to 1 output
        self.linear2 = nn.Linear(3, 1)
        # Sigmoid activation for the output layer (for binary classification)
        self.sigmoid = nn.Sigmoid()

    # Define the forward pass of the model
    def forward(self, feature):
        out = self.linear1(feature) # Apply first linear transformation
        out = self.relu(out)        # Apply ReLU activation
        out = self.linear2(out)     # Apply second linear transformation
        out = self.sigmoid(out)     # Apply sigmoid activation
        return out

In [36]:
# Create a dummy dataset with 10 samples and 5 features
features = torch.rand(10, 5)

# Create an instance of Model2
model = Model2(features.shape[1]) # Pass the number of features (5)

# Call the model's forward pass
output = model(features)
print("Output from Model2:\n", output)

Output from Model2:
 tensor([[0.5470],
        [0.5391],
        [0.5440],
        [0.5345],
        [0.5349],
        [0.5361],
        [0.5430],
        [0.5369],
        [0.5427],
        [0.5523]], grad_fn=<SigmoidBackward0>)


In [37]:
# Access and print the weights and biases of the linear layers in Model2
print("Linear 1 weights:\n", model.linear1.weight)
print("Linear 1 bias:\n", model.linear1.bias)
print("Linear 2 weights:\n", model.linear2.weight)
print("Linear 2 bias:\n", model.linear2.bias)

Linear 1 weights:
 Parameter containing:
tensor([[ 0.1608,  0.1538,  0.0517, -0.1819, -0.4281],
        [-0.1532,  0.3646,  0.2324, -0.2530, -0.3396],
        [-0.4447,  0.2141, -0.2106,  0.1058,  0.0581]], requires_grad=True)
Linear 1 bias:
 Parameter containing:
tensor([ 0.2777,  0.0834, -0.3649], requires_grad=True)
Linear 2 weights:
 Parameter containing:
tensor([[ 0.2268, -0.2152, -0.0990]], requires_grad=True)
Linear 2 bias:
 Parameter containing:
tensor([0.1307], requires_grad=True)


In [38]:
# Display a summary of the Model2 architecture
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model2                                   [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [39]:
# Define another multi-layer perceptron (MLP) using nn.Sequential
class Model3(nn.Module):

    # Initialize the model with the number of input features
    def __init__(self, no_of_features):
        super().__init__()
        # Define the network as a sequential container of layers
        self.network = nn.Sequential(
            nn.Linear(no_of_features, 3), # First linear layer
            nn.ReLU(),                    # ReLU activation
            nn.Linear(3, 1),              # Second linear layer
            nn.Sigmoid()                  # Sigmoid activation
        )

    # Define the forward pass
    def forward(self, feature):
        out = self.network(feature) # Pass the input through the sequential network
        return out

In [40]:
# Create a dummy dataset with 10 samples and 5 features
features = torch.rand(10, 5)

# Create an instance of Model3
model = Model3(features.shape[1]) # Pass the number of features (5)

# Call the model's forward pass
output = model(features)
print("Output from Model3:\n", output)

Output from Model3:
 tensor([[0.3941],
        [0.3920],
        [0.3933],
        [0.3576],
        [0.3901],
        [0.3697],
        [0.3629],
        [0.3474],
        [0.3846],
        [0.3946]], grad_fn=<SigmoidBackward0>)


In [41]:
# Access and print the weights and biases of the linear layers in Model3
# When using nn.Sequential, layers are accessed by index from the 'network' attribute.
print("Linear 1 weights:\n", model.network[0].weight)
print("Linear 1 bias:\n", model.network[0].bias)
print("Linear 2 weights:\n", model.network[2].weight)
print("Linear 2 bias:\n", model.network[2].bias)

Linear 1 weights:
 Parameter containing:
tensor([[-0.2406, -0.1621, -0.0199,  0.0699, -0.0681],
        [-0.4165,  0.0575, -0.1781,  0.3849, -0.0160],
        [ 0.3084, -0.3831, -0.3538, -0.1139,  0.1315]], requires_grad=True)
Linear 1 bias:
 Parameter containing:
tensor([-0.1323,  0.3266,  0.1536], requires_grad=True)
Linear 2 weights:
 Parameter containing:
tensor([[-0.0480,  0.4472, -0.2139]], requires_grad=True)
Linear 2 bias:
 Parameter containing:
tensor([-0.5629], requires_grad=True)


In [42]:
# Display a summary of the Model3 architecture
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model3                                   [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00