<a href="https://colab.research.google.com/github/sjagadee/py_torch_from_basics/blob/main/04_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch, torch.nn as nn


In [3]:
# create class for model
class Model(nn.Module):

    def __init__(self, no_of_features):
        super().__init__()
        self.linear = nn.Linear(no_of_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, feature):
        out = self.linear(feature) # wx + b
        out = self.sigmoid(out)
        return out

In [4]:
# create a data set
features = torch.rand(10, 5)

# create the model
model = Model(features.shape[1])

# call model's forward pass
# model.forward(features) # can be used using magic functions in pytorch
model(features)

tensor([[0.3546],
        [0.4862],
        [0.4261],
        [0.4031],
        [0.3757],
        [0.4333],
        [0.3311],
        [0.4022],
        [0.3566],
        [0.3779]], grad_fn=<SigmoidBackward0>)

In [6]:
# can check weights
print(model.linear.weight)
print(model.linear.bias)

Parameter containing:
tensor([[-0.2455,  0.2713,  0.2990, -0.2025, -0.0230]], requires_grad=True)
Parameter containing:
tensor([-0.4180], requires_grad=True)


In [7]:
! pip install torchinfo

In [8]:
from torchinfo import summary
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00